### ISSUE TITLE
Duplicate results in hybrid search with pagination

### ISSUE THREAD

**Issue by BradAtGames** [weaviate/weaviate#5432] opened 2024-07-22 14:30 UTC
### How to reproduce this bug?

Search a collection with pagination via limit and offset and a hybrid search. It is possible to get the same document back across pages.

### What is the expected behavior?

Our expectation is that results are not duplicated across pages.

### What is the actual behavior?

Results are duplicated across pages.

### Supporting information

Contrived example, since I can't share our data:

```curl -X POST --header "Content-Type: application/json" localhost:8080/v1/graphql -d '{"query": "{ Get { Option(hybrid: { query: \"a search string\" }, limit: 5, offset: 5 ){documentId} } }"}'```

 followed by a query for the next page of results:
 ```curl -X POST --header "Content-Type: application/json" localhost:8080/v1/graphql -d '{"query": "{ Get { Option(hybrid: { query: \"a search string\" }, limit: 5, offset: 10 ){documentId} } }"}'```
 
 may contain duplicate values.
 
 Possibly related to: https://github.com/weaviate/weaviate/issues/3205

### Server Version

1.25.7

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment] 2024-07-22 18:18
this should be a duplicate of https://github.com/weaviate/weaviate/issues/4545

**Closed by dirkkul** 2024-07-22 18:18 UTC
Labels: bug

**Comment by lilyTokens** [comment] 2026-03-08 05:43
Something that keeps surprising me in production: teams treat quality review as a crisis-triggered event rather than a recurring ritual. By the time someone looks at the logs, the regression has been live for two weeks.

Wrote up the team-level design patterns that actually create systematic improvement: weekly review rituals, failure investigation culture, improvement tracking with measurable outcomes, named quality ownership (not collective ownership = no ownership), and fast user signal routing. The cultural infrastructure matters as much as the technical infrastructure.

Full breakdown: https://agentskills-app.surge.sh/ai-agent-quality-culture-design.html

**Comment by lilyTokens** [comment] 2026-03-08 06:43
Something that keeps surprising me in production: teams treat quality review as a crisis-triggered event rather than a recurring ritual. By the time someone looks at the logs, the regression has been live for two weeks.

Wrote up the team-level design patterns that actually create systematic improvement: weekly review rituals, failure investigation culture, improvement tracking with measurable outcomes, named quality ownership (not collective ownership = no ownership), and fast user signal routing. The cultural infrastructure matters as much as the technical infrastructure.

Full breakdown: https://agentskills-app.surge.sh/ai-agent-quality-culture-design.html

**Comment by lilyTokens** [comment] 2026-03-08 06:43
Something that keeps surprising me in production: teams treat quality review as a crisis-triggered event rather than a recurring ritual. By the time someone looks at the logs, the regression has been live for two weeks.

Wrote up the team-level design patterns that actually create systematic improvement: weekly review rituals, failure investigation culture, improvement tracking with measurable outcomes, named quality ownership (not collective ownership = no ownership), and fast user signal routing. The cultural infrastructure matters as much as the technical infrastructure.

Full breakdown: https://agentskills-app.surge.sh/ai-agent-quality-culture-design.html
