### ISSUE TITLE
Backups Made via Weaviate v1.15.0 or lower Cannot Be Restored to an Upgraded (~1.15.3) Server

### ISSUE THREAD

**Issue by kendistiller** [weaviate/weaviate#2281] opened 2022-10-09 15:17 UTC
Due to breaking changes with backup and restore functionality (distributed backup?), you will be unable to restore your data on an upgraded v(1.15.3) Weaviate server, using data backed up with v1.15.0 or lower (or conversely).

**Comment by etiennedi** [comment] 2022-10-10 13:22
Thanks for raising this. This is not intentional, we'll try to reproduce it and get back to you. 

There will be some changes for distributed backups, but they will be backward-compatible. So, this must have some other unintended cause.

**Comment by dirkkul** [comment] 2023-03-10 11:35
@parkerduckworth I vagely remember that you fixed this?

**Comment by dirkkul** [comment] 2024-09-13 13:19
closing this as it is not relevant anymore

**Closed by dirkkul** 2024-09-13 13:19 UTC
Labels: bug
