### ISSUE TITLE
Invalid schema properties don't throw an error

### ISSUE THREAD

**Issue by krlng** [weaviate/weaviate#3028] opened 2023-05-16 09:20 UTC
This is a minor problem. The client validates the schema on top-level, how ever if an error is within on of the properties, it just silently fails and does not create a schema. 

An example would be forgetting which text2vec module should be used: `text2vec-` => `text2vec-openai`

```
schema = {
      "class": "Document",
      "description": "A class called document",
      "vectorizer": "text2vec-openai",
      "properties": [
        {
          "name": "content",
          "dataType": [ "text" ],
          "moduleConfig": {
            "text2vec-": {
              "skip": False,
              "vectorizePropertyName": False
            }
          },
        },
      ]
    }

client.schema.create_class(schema)
```

Using weaviate:1.19.0 and weaviate-client==3.18.0

**Comment by dirkkul** [comment] 2024-10-21 14:57
duplicate of https://github.com/weaviate/weaviate/issues/3111

**Closed by dirkkul** 2024-10-21 14:57 UTC
