### ISSUE TITLE
Feature Request: BM25/Hybrid: Support ANDing query terms (currently always ORed).

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate#2520] opened 2023-01-12 08:08 UTC
When the query is "cozy fish restaurant" , the bm25 operator (as at v1.17.0) will perform a search based on:

"cozy" OR "fish" OR "restaurant"

we could add a boolean variable to the operator e.g. `all_terms_must_match` that when set to true, will perform a search based on:

"cozy" AND "fish" AND "restaurant"

or, we could consider other approaches if we want the user to be able to customise the search using boolean operators themselves e.g.

"cozy" AND ("fish"  OR  NOT "restaurant")

**Comment by etiennedi** [comment] 2023-01-12 08:45
Great idea!

From an API perspective, I think it would be great if we had a field `operator`.

This would default to `operator: Or` which is the current behavior. As part of this, we could add the second option` operator: And`. But it would also give us space to introduce other operators such as `Wand`, `BlockWand`, etc. in the future. (cc @trengrj, @byronvoorbach)

**Comment by dirkkul** [comment] 2024-10-21 11:11
duplicate of https://github.com/weaviate/weaviate/issues/2688

**Closed by dirkkul** 2024-10-21 11:11 UTC
Labels: backlog
