### ISSUE TITLE
How to increase the Weaviate disk limit

### ISSUE THREAD

**Issue by PolarPeak** [weaviate/weaviate#5912] opened 2024-09-27 02:38 UTC
### Describe your feature request

How to increase the Weaviate disk limit, even though the usage is 90%, my disk still has 1TB of free space, and there are no more files to clean up.

{"action":"read_disk_use","level":"warning","msg":"disk usage currently at 89.52%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2024-09-26T04:52:31Z"}

[2024-09-26 03:16:43,377: INFO/MainProcess] Start process document: ce79ecce-445b-4835-9052-720c7491dc5b
[2024-09-26 03:16:47,939: WARNING/MainProcess] {'error': [{'message': 'store is read-only'}]}
[2024-09-26 03:16:47,993: INFO/MainProcess] Processed dataset: 896b6e41-8c92-4090-96cf-50bd643e1c7c latency: 4.618616024963558
[2024-09-26 03:16:48,008: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[9423068a-d1c4-48a9-9730-d1519d697d6d] succeeded in 4.634086176753044s: None

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment] 2024-10-01 09:33
hi @PolarPeak !!

This can be set as an environment variable for your Weaviate instance:

https://weaviate.io/developers/weaviate/config-refs/env-vars#general

You need to change the values for `DISK_USE_READONLY_PERCENTAGE` and `DISK_USE_WARNING_PERCENTAGE`.

For this kind of questions, please feel free to reach us at https://forum.weaviate.io/

I will close this issue as this is not a bug nor a feature request.

Thanks!

**Closed by dudanogueira** 2024-10-01 09:33 UTC
Labels: feature request
