### ISSUE TITLE
Weaviate vectorizer `ref2vec-centroid` not computing vector after PUT on object references

### ISSUE THREAD

**Issue by danielknode** [weaviate/weaviate#3185] opened 2023-06-29 00:03 UTC
**Weaviate version**: 1.19.9 (WCS)

I have configured class `Foo` to use the `ref2vec-centroid` vectorizer module on the property `belongsTo` which cross-references `Bar`:
```json
[
  {
    "class": "Foo",
    "vectorizer": "ref2vec-centroid",
    "moduleConfig": {
      "ref2vec-centroid": {
        "referenceProperties": ["belongsTo"],
        "method": "mean"
      }
    },
    "properties": [
      {
        "name": "belongsTo",
        "dataType": ["Bar"],
      },
    ]
  },
  {
    "class": "Bar",
    "vectorizer": "text2vec-openai",
    "moduleConfig": {
      "text2vec-openai": {
        "model": "ada",
        "modelVersion": "002",
        "type": "text"
      }
    },
    "properties": [...]
  }
]
```

I created a `Foo` and `Bar` objects (without reference) and verified the vector exists on `Bar` object. Then I run the following to update the reference from `Foo` to `Bar` which calls PUT on object references endpoint:
```python
import weaviate

client = # create Weaviate client

foo_uuid = # create Foo object
bar_uuid = # create Bar object

client.data_object.reference.update(
    from_class_name="Foo",
    from_uuid=foo_uuid,
    from_property_name="belongsTo",
    to_class_names="Bar",
    to_uuids=[bar_uuid]
)
```

According to the `ref2vec-centroid` module [documentation](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/ref2vec-centroid#updating-the-centroid) I would expect the Foo objects vector to now be computed, but a Get GQL query to retrieve vector for the object returns null as the vector.

**Comment by dirkkul** [comment] 2024-10-21 15:01
I think this is a duplicate of https://github.com/weaviate/weaviate/issues/2654

**Closed by dirkkul** 2024-10-21 15:01 UTC
