### ISSUE TITLE
shard="bwsSXyinFlVm": store is read-only'}

### ISSUE THREAD

**Issue by sunnyl95** [weaviate/weaviate#5297] opened 2024-07-04 12:29 UTC
### How to reproduce this bug?

 # my code
        db_info_collection.data.insert(
            {
                "name": region_name,
                "rel_table_collection": table_collection_name,
                "rel_column_collection": column_collection_name,
            }
        )
        
    

### What is the expected behavior?

can successfully  write  to collection.

### What is the actual behavior?

   when run this code ,will get error:
        Object was not added! Unexpected status code: 500, with response body: {'error': [{'message': 'put object: import into index db_info_collection: put local object: shard="bwsSXyinFlVm": store is read-only'}]}.
        

### Supporting information

2024-07-04 20:17:05,177 - callback - apis.py:111 - ERROR - Error processing message: Object was not added! Unexpected status code: 500, with response body: {'error': [{'message': 'put object: import into index db_info_collection: put local object: shard="bwsSXyinFlVm": store is read-only'}]}.

### Server Version

       weaviate-client ==4.6.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment] 2024-07-08 21:07
hi @sunnyl95 !

This is not a bug. Whenever Weaviate [reaches a disk limit, defined as documented here](https://weaviate.io/developers/weaviate/configuration/persistence#disk-pressure-warnings-and-limits), it will set the shards to READONLY.

After provisioning more disk space to your cluster, you can set the shards to READY again:
https://weaviate.io/developers/weaviate/manage-data/collections#update-shard-status

I will close this issue for now, but please, feel free to open a thread in https://forum.weaviate.io/ if you need assistance with that.

Thanks!

**Closed by dudanogueira** 2024-07-08 21:07 UTC
Labels: bug
