### ISSUE TITLE
The StatefulSet does not handle pod replacement well

### ISSUE THREAD

**Issue by bstoutenburgh** [weaviate/weaviate#3045] opened 2023-05-19 19:53 UTC
We have had repeated outages with our StatefulSet on our clusters and it has been noted during these outages that one pod in the set will complain about Conflicting address.

<details>
<summary>Sample weaviate-1 logs...</summary>

```
...
{"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2023-05-17T15:10:31Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T03:12:34Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T03:12:36Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 1","time":"2023-05-18T03:12:37Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 1","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 1","time":"2023-05-18T03:12:38Z"}
{"level":"info","msg":" memberlist: Marking weaviate-0 as failed, suspect timeout reached (0 peer confirmations)","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.172.234:7000 Theirs: 10.30.168.191:7000 Old state: 2","time":"2023-05-18T03:12:38Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T03:12:40Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:08:16Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:08:19Z"}
{"level":"info","msg":" memberlist: Marking weaviate-0 as failed, suspect timeout reached (0 peer confirmations)","time":"2023-05-18T13:08:20Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:08:23Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:29Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:30Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.168.191:7000 Theirs: 10.30.162.222:7000 Old state: 2","time":"2023-05-18T13:08:30Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:16:19Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:21Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:21Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:21Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:21Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:21Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:22Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:22Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:16:22Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:22Z"}
{"level":"error","msg":" memberlist: Conflicting address for weaviate-0. Mine: 10.30.162.222:7000 Theirs: 10.30.166.92:7000 Old state: 1","time":"2023-05-18T13:16:22Z"}
{"level":"info","msg":" memberlist: Marking weaviate-0 as failed, suspect timeout reached (0 peer confirmations)","time":"2023-05-18T13:16:23Z"}
{"level":"info","msg":" memberlist: Suspect weaviate-0 has failed, no acks received","time":"2023-05-18T13:16:25Z"}
```
</details>

In this case the `weaviate-0` pod had been redeployed (a Kubernetes node was replaced) and between the headless service and `weaviate-1` our application just could not perform searches until `weaviate-1` had been replaced.

We have verified:
  - `CLUSTER_GOSSIP_BIND_PORT` was _7000_
  - `CLUSTER_DATA_BIND_PORT` was _7001_
  - the headless Service has `.spec.publishNotReadyAddresses` set to _true_ and `.spec.targetPort` is _7000_
  - both pods were being Ready and returning "200 OK" on the liveness path

We have seen this multiple times in the past couple months, but today we are using chart 16.0.0, weaviate tag 1.19.0.

Any number of events on a cluster can cause pod cycling so we need this to be more self-healing.

**Comment by etiennedi** [comment] 2023-05-20 11:37
cc @redouan-rhazouani @antas-marcin 

Could it be that we're not doing a graceful shutdown with memberlist somehow? Since we use a StatefulSet we have the guarantee that every pod exists only once. This sounds like the pod would have to do something as it shuts down to "free" its name so it doesn't lead to an IP conflict once it comes back up (potentially with a different IP).

**Comment by bstoutenburgh** [comment] 2023-05-20 14:24
For what it's worth we're experiencing another outage today, possibly related cause with slightly different log messages.

From weaviate-0:
```json
{"level":"error","msg":" memberlist: Failed to push local state: write tcp 10.30.171.15:7000-\u003e10.30.205.64:36268: i/o timeout from=10.30.205.64:36268","time":"2023-05-19T16:23:24Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-1 failed: write tcp 10.30.171.15:42692-\u003e10.30.205.64:7000: i/o timeout","time":"2023-05-19T16:23:24Z"}
{"level":"error","msg":" memberlist: Failed to push local state: write tcp 10.30.171.15:7000-\u003e10.30.205.64:39430: i/o timeout from=10.30.205.64:39430","time":"2023-05-19T19:53:35Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-1 failed: write tcp 10.30.171.15:52144-\u003e10.30.205.64:7000: i/o timeout","time":"2023-05-19T19:53:35Z"}
{"level":"error","msg":" memberlist: failed to receive and remove the stream label header: read tcp 10.30.171.15:7000-\u003e10.30.205.64:42584: i/o timeout from=\u003cunknown address\u003e","time":"2023-05-20T09:19:48Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-1 failed: read tcp 10.30.171.15:34520-\u003e10.30.205.64:7000: i/o timeout","time":"2023-05-20T09:19:56Z"}
```

From weaviate-1:
```json
{"level":"error","msg":" memberlist: failed to receive and remove the stream label header: read tcp 10.30.205.64:7000-\u003e10.30.171.15:42692: i/o timeout from=\u003cunknown address\u003e","time":"2023-05-19T16:22:57Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-0 failed: read tcp 10.30.205.64:36268-\u003e10.30.171.15:7000: i/o timeout","time":"2023-05-19T16:23:11Z"}
{"level":"error","msg":" memberlist: failed to receive and remove the stream label header: read tcp 10.30.205.64:7000-\u003e10.30.171.15:52144: i/o timeout from=\u003cunknown address\u003e","time":"2023-05-19T19:53:07Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-0 failed: read tcp 10.30.205.64:39430-\u003e10.30.171.15:7000: i/o timeout","time":"2023-05-19T19:53:24Z"}
{"level":"error","msg":" memberlist: Failed to push local state: write tcp 10.30.205.64:7000-\u003e10.30.171.15:34520: i/o timeout from=10.30.171.15:34520","time":"2023-05-20T09:20:16Z"}
{"level":"error","msg":" memberlist: Push/Pull with weaviate-0 failed: write tcp 10.30.205.64:42584-\u003e10.30.171.15:7000: i/o timeout","time":"2023-05-20T09:20:16Z"}
```

Endpoints and pods:
```
❯ k get endpoints -l app.kubernetes.io/name=weaviate -o wide
NAME                     ENDPOINTS                                                 AGE
qna-transformers         10.30.163.226:8080,10.30.199.155:8080                     32d
transformers-inference   10.30.160.219:8080,10.30.182.210:8080,10.30.194.49:8080   32d
weaviate                 10.30.171.15:8080,10.30.205.64:8080                       32d
weaviate-headless        10.30.171.15:7000,10.30.205.64:7000                       32d

❯ k get pods -l app.kubernetes.io/name=weaviate -o wide
NAME         READY   STATUS    RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
weaviate-0   1/1     Running   0          23h   10.30.171.15   ip-10-30-164-111.ec2.internal   <none>           <none>
weaviate-1   1/1     Running   0          23h   10.30.205.64   ip-10-30-205-195.ec2.internal   <none>           <none>
```

**Comment by gkaskonas** [comment] 2023-10-12 15:10
Had the same issue when updating a 3 pod set up. All I did was update an environment variable and pod-2 would not come up.

Had to kill all the pods and start from scratch to get the cluster running again.

**Comment by fdammeke** [comment] 2024-02-19 12:10
I can confirm, also running into this issue
Chart release: `16.8.1`
Weaviate image tag: `1.23.9`

**Action**: restart one POD from a 3 replica setup

**Result**:
The remaining POD log entry:
```json
{"level":"error","msg":" memberlist: Conflicting address for weaviate-1. Mine: 10.131.1.124:7000 Theirs: 10.131.1.125:7000 Old state: 2","time":"2024-02-19T11:53:51Z"}
```

The restarted POD doesn't start anymore, error log:
```json
{"level":"warning","msg":" memberlist: Refuting a suspect message (from: weaviate-1)","time":"2024-02-19T11:53:52Z"}
{"level":"info","msg":"No resource limits set, weaviate will use all available memory and CPU. To limit resources, set LIMIT_RESOURCES=true","time":"2024-02-19T11:53:52Z"}
{"action":"broadcast_abort_transaction","error":"host \"10.129.4.163:7001\": unexpected status code 401: ","id":"52588276-976f-4315-9211-0073474f497a","level":"error","msg":"broadcast tx abort failed","time":"2024-02-19T11:53:52Z"}
{"action":"startup","error":"could not load or initialize schema: sync schema with other nodes in the cluster: read schema: open transaction: broadcast open transaction: host \"10.129.4.163:7001\": unexpected status code 401 ()","level":"fatal","msg":"could not initialize schema manager","time":"2024-02-19T11:53:52Z"}
```

Temporary **bypass** of issue:
Scale StatefulSet to 0 and scale up again, which obviously leads to downtime.

**Comment by dirkkul** [comment] 2024-10-21 04:31
this should not be an issue anymore with RAFT, closing this

**Closed by dirkkul** 2024-10-21 04:31 UTC
Labels: bug
