### ISSUE TITLE
High CPU usage in `memwatch.(*Monitor).calculateCurrentUsage`

### ISSUE THREAD

**Issue by prattmic** [weaviate/weaviate#3777] opened 2023-11-15 19:46 UTC
I happened to be running https://github.com/weaviate/weaviate-benchmarking and profiling at various points, and I noticed what seemed like rather high usage in `memwatch.(*Monitor).calculateCurrentUsage`, upwards of 15% of cycles:

![image](https://github.com/weaviate/weaviate/assets/1293187/cb7572e3-a35d-4496-a45e-931b45b44676)

This is most prominent during loading or validation, which seems to be mostly single-threaded, not during the actual speed test, which is parallelized.

Collecting an entire heap profile to calculate the live heap size seems like overkill, and is certainly quite expensive.

If I am understanding the rationale in https://github.com/weaviate/weaviate/pull/2220 correctly, then the [`runtime/metrics`](https://pkg.go.dev/runtime/metrics) `/gc/heap/live:bytes` metric provides exactly what you are looking for: "Heap memory occupied by live objects that were marked by the previous GC." Getting the value of a `runtime/metrics` metric is ~free.

cc @etiennedi

**Comment by etiennedi** [comment] 2023-11-15 21:18
Hi @prattmic,

Thanks for bringing this up. One question up front: Which version of the Weaviate server are you running? There was a bug in the logic outlined above that was fixed in https://github.com/weaviate/weaviate/pull/2629. Seems this was patched in v1.17.x – not sure which version exactly. Any chance you're running into this?

Nevertheless, what you say makes sense. Might be a bit overkill to get a whole profile, just to get the total sum. That said, since #2629 I haven't really seen this logic appear anywhere in profiles.

Side-note: If you're looking for good performance end-to-end, I would highly recommend using the latest version (1.22.x) in combination with the gPRC API. For querying that is officially supported in the `v4` Python client. It's not yet in the other clients, but it's fairly easy to auto-gen a client from the protobuf definitions. As your profile also shows, an unreasonable amount of time is spent on GraphQL-related activity and in addition a lot of the GC-work is caused by GraphQL-specific allocations. (cc @trengrj who is currently reworking the benchmarking scripts and might be able to share some helpful code)

**Comment by prattmic** [comment] 2023-11-15 21:47
I'm running at approximately HEAD (764935fe4b576c87750d6a16ea20fd6c349b20b8, specifically). I'm not trying to run Weaviate for real; I work on the Go compiler/runtime and I've been benchmarking/profiling various large Go applications to investigate the effects of optimization work we are doing.

I could believe that this never shows up for real in real production settings. It just stood out on my profile and seemed like low-hanging fruit, so I figured I'd let you know. I've never seen a project collecting a heap profile to measure live heap size. :)

**Comment by etiennedi** [comment] 2023-11-15 21:52
Gotcha. That makes a lot of sense and as you say should be easy enough to improve.

> I work on the Go compiler/runtime and I've been benchmarking/profiling various large Go applications

This is extremely interesting. Would love to chat about this if you have some time in the coming days. We're very interested in all things performance and if there's anything we can do to help you make Go better, we'd love to help. (At least partially also for selfish reasons that we could benefit directly).

**Comment by prattmic** [comment] 2023-11-15 22:56
Sure, I'd be happy to talk. Feel free to shoot me an email, `mpratt AT google.com`

**Comment by etiennedi** [comment] 2023-11-16 10:33
Oh, haha, just saw that the `/gc/heap/live:bytes` metrics is brand new in Go 1.21 ... because the 1.20-based tests on CI failed ;-)

**Comment by prattmic** [comment] 2023-11-16 15:40
Ah, indeed, I'd forgotten that one is new.

**Comment by dirkkul** [comment] 2024-10-18 11:21
Looks like this was resolved

**Closed by dirkkul** 2024-10-18 11:21 UTC
Labels: autoclosed
