### ISSUE TITLE
AWS Bedrock Embedding doesn't work

### ISSUE THREAD

**Issue by kobrinartem** [weaviate/weaviate#3940] opened 2023-12-20 16:31 UTC
### How to reproduce this bug?

# Run weaviate through docker compose:
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-aws'
      ENABLE_MODULES: 'text2vec-aws'
      CLUSTER_HOSTNAME: 'node1'

Then run python code
import weaviate

client = weaviate.Client(
    url = "http://127.0.0.1:8080",  # Replace with your endpoint
    auth_client_secret=...# Replace w/ your Weaviate instance API key
    additional_headers={
        "X-AWS-Access-Key": "....",
        "X-AWS-Secret-Key": "....",
    }
)

# create schema
class_obj = {
    "class": "Article",
    "description": "A class called document",
    "vectorizer": "text2vec-aws",
    "vectorIndexConfig": {
    "distance": "cosine"
    },
    "moduleConfig": {
        "text2vec-aws": {
            "model": "amazon.titan-embed-text-v1",
            "region": "eu-central-1",
            "vectorizeClassName": False,
        }
    },
    "properties": [
        {
        "name": "title",
        "dataType": [
            "text"
        ]
        },
        {
        "name": "body",
        "dataType": [
            "text"
        ]
        },
    ]
}

client.schema.create_class(class_obj) 

# add data
client.data_object.create(
        class_name="Article",
        data_object={
                    "title": "test",
                    "body": "test",
                }
    )

### What is the expected behavior?

It should process the data with AWS Bedrock

My assumption that we use wrong url:
POST https://bedrock-runtime.us-east-1.amazonaws.com/model/amazon.titan-text-express-v1/invoke

-H accept: */*  
-H content-type: application/json

Payload
{"inputText": "Hello world"} 

### What is the actual behavior?

I got the error:

rag-weaviate-weaviate-1  | {"action":"requests_total","api":"rest","class_name":"Article","error":"update vector: send POST request: send POST request: Post \"https://bedrock.eu-central-1.amazonaws.com/model/amazon.titan-embed-text-v1/invoke\": context canceled","level":"error","msg":"unexpected error","query_type":"objects","time":"2023-12-20T16:14:12Z"}
rag-weaviate-weaviate-1  | {"action":"read_disk_use","level":"warning","msg":"disk usage currently at 85.44%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2023-12-20T16:22:25Z"}

### Supporting information

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html

### Server Version

1.23.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by kobrinartem** [comment] 2023-12-22 12:56
tested on us-west-2:

weaviate-aws-weaviate-1  | {"action":"requests_total","api":"rest","class_name":"Article","error":"update vector: send POST request: send POST request: Post \"https://bedrock-runtime.us-west-2.amazonaws.com/model/cohere.embed-multilingual-v3/invoke\": context canceled","level":"error","msg":"unexpected error","query_type":"objects","time":"2023-12-22T12:55:40Z"}

**Comment by kobrinartem** [comment] 2023-12-22 15:55
when I tried cloud version I got another error:

```
uuid = client.data_object.create(
    class_name="Article",
    data_object={
            "title": "test",
            "body": "test content",
        }
)
```

File [~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:975](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:975), in Response.json(self, **kwargs)
    [971](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:971)     return complexjson.loads(self.text, **kwargs)
    [972](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:972) except JSONDecodeError as e:
    [973](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:973)     # Catch JSON-related errors and raise as requests.JSONDecodeError
    [974](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:974)     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> [975](https://file+.vscode-resource.vscode-cdn.net/Users/artemkobrin/repositories/peakdefence/nl-shared-lib/src/templates/rag-weaviate/weaviate-aws/~/repositories/peakdefence/.venv/lib/python3.11/site-packages/requests/models.py:975)     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by sandeepchandra** [comment] 2024-02-29 09:17
I encountered a similar challenge while attempting to generate embeddings using the AWS Bedrock model - amazon.titan-embed-text-v1. Utilizing a Docker setup with the image semitechnologies/weaviate:1.23.9, I aimed to add batch objects to the weaviate vector database. But ended up with read timeouts and invalid bedrock API URL (which doesn't have 'bedrock-runtime' in the domain) as above.

To resolve the issue, I conducted an investigation into the code of the Weaviate repository (master branch). It appears that within the codebase, there exists a conditional statement that distinguishes the URL creation for model IDs beginning with 'cohere' and 'amazon'. A snippet of this code is depicted below:

![image](https://github.com/weaviate/weaviate/assets/32015702/69a2bbcd-b2da-421b-a23e-5b337e25408f)

Having identified this condition, I proceeded to remove it, thereby allowing for the creation of the service name regardless of the model ID. Subsequently, I rebuilt the Docker image and applied it within my use-case, resulting in the desired outcomes.

**Comment by bbeaumatin** [comment] 2024-03-25 14:02
Hello, bumping this a little bit. There is indeed a bug here preventing from using the titan embedding model, as the URL is supposed to start with "bedrock-runtime" and given this condition in the code shown by @sandeepchandra it is not possible to build the URL properly, then the vectorization doesn't work. I'm not much of a Go developer but if needed I can propose a PR. Let me know if it's needed or if I misunderstood the configuration to do to have the titan model working. Thanks!

**Comment by IzioDev** [comment] 2024-04-18 14:37
URL should be : `https://bedrock-runtime.${REGION}.amazonaws.com/model/${MODEL_ID}/invoke` for Bedrock service

**Comment by chrisk314** [comment] 2024-05-07 10:50
We're also hitting this. Any update on timeline for the fix?

**Comment by antas-marcin** [comment] 2024-05-07 11:40
Hello, I'm working on fixing this issue, I think that I will be able to fix this by Thursday (maybe even sooner), once this is resolved I will write about this here

**Comment by antas-marcin** [comment] 2024-05-08 20:13
I have a PR ready that fixes Bedrock support. I hope to merge it tomorrow and hopefully make a patch release on Friday.

**Comment by antas-marcin** [comment] 2024-05-08 21:33
If you want to test it here's a preview docker image:
```
semitechnologies/weaviate:preview-fix-text2vec-aws-module-bedrock-support-730b4c5
```

I have added support for `AWS_SESSION_TOKEN` in the module if one wants to pass using headers then `X-Aws-Session-Token` header should be used for that

**Comment by chrisk314** [comment] 2024-05-09 10:23
@antas-marcin I can confirm this is working for us now using the preview docker image. Thanks for the fix! Looking forward to the patch release.

P.S. I could not see any evidence of the calls to Bedrock in the Weaviate logs. I know it's all working correctly because my integration test is passing; however, even with debug or trace level logging I can't see any reference to the calls to the Bedrock service in the logs. I see a lot of messages in the logs like the below example when I add an item to Weaviate. There is a path shown but no host. Would be nice if the logs actually showed the Bedrock service url.
```text
{"action":"restapi_request","level":"debug","method":"GET","msg":"received HTTP request","time":"2024-05-09T09:51:31Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/nodes","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
```

**Comment by antas-marcin** [comment] 2024-05-09 18:50
@chrisk314 we have switched to AWS SDK and now the Bedrock service URL is being generated internally by SDK, we don't control it anymore. And yes, you are right, we don't log the requests to Bedrock.

btw we have released [v1.24.12](https://github.com/weaviate/weaviate/releases/tag/v1.24.12) which contains a fix for this issue.

**Comment by chrisk314** [comment] 2024-05-10 10:12
@antas-marcin ok thanks for confirming on the logs and for the patch release.

**Comment by antas-marcin** [comment] 2024-05-10 10:45
Thank you @chrisk314! I will resolve this issue now

**Closed by antas-marcin** 2024-05-10 10:45 UTC
Labels: bug
