### ISSUE TITLE
ContainsAny does not work

### ISSUE THREAD

**Issue by phongcodelink** [weaviate/weaviate#3429] opened 2023-08-22 03:27 UTC
Hi, I got this issue on v1.21.0 with the new ContainsAny filter. Do you have any idea it does not work?

Here is my class definition
```
    article = {
        "class": "Article",
        "vectorizer": "text2vec-openai",
        "vectorIndexConfig": {
            "distance": "cosine",
        },
        "moduleConfig": {
            "generative-openai": {}
        },
        "properties": [
            {
                "name": "question",
                "dataType": ["text"]
            },
            {
                "name": "answer",
                "dataType": ["text"]
            },
            {
                "name": "language",
                "dataType": ["text"]
            },
            {
                "name": "languages",
                "dataType": ["text[]"]
            }
        ],
    }
```

Here is my graphql query
```
{
  Get {
    Article (
      where: {
        path: "languages",
        operator: ContainsAny,
        valueText: ["en"]
      }
    )
    {
      question
    }
  }
}
```

Here is the error message
  "message": "explorer: list class: search: object search at index article: remote shard object search J1am8r76jCKa: unexpected status code 500 (shard article_J1am8r76jCKa: value type should be []string but is []interface {}\n)"

**Comment by dudanogueira** [comment] 2023-08-23 18:43
Hi! Welcome to our community :hugs: 

I could not reproduce this error. Here is a notebook of what I did:
https://colab.research.google.com/drive/1LLOQj3q1MRWKbY35rPV7uapZfXOy6PB5?authuser=1#scrollTo=7EaGKMgUp3dI

Let me know if this helps. I will close this issue for now.

Please, feel free to reopen or, preferably, bring this discussion to our [forum](https://forum.weaviate.io/).

Thanks!

**Closed by dudanogueira** 2023-08-23 18:43 UTC

**Comment by felixng313** [comment] 2023-10-28 12:17
+1

**Comment by felixng313** [comment] 2023-10-28 14:20
The issue is occurring in a cluster where the data is stored on a remote node.
