### ISSUE TITLE
explainScore containing only one score when performing hybrid search

### ISSUE THREAD

**Issue by Techie5879** [weaviate/weaviate#4735] opened 2024-04-21 10:31 UTC
### How to reproduce this bug?

In some cases, when performing hybrid search, the explainScore contains both scores for keyword and vector searches. For example:
```
Hybrid (Result Set vector) Document 2d628e6a-565c-47b3-8e8a-6c0924358ec0: original score 0.3755169, normalized score: 0.35678205 - 
Hybrid (Result Set keyword) Document 2d628e6a-565c-47b3-8e8a-6c0924358ec0: original score 6.4637876, normalized score: 0.4792187
```

However, in other cases, we do not have the 2nd score, and there is just vector or keyword. Is this expected?
```
Hybrid (Result Set vector) Document fb44de08-ac8b-420a-b203-63825fb8bfb2: original score 0.34787154, normalized score: 0.23426087
```

Why are the two results not being combined in these cases?

### What is the expected behavior?

Two results should be combined

### What is the actual behavior?

Only single result

### Server Version

1.24.8

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dudanogueira** [comment] 2024-05-06 20:01
Hi! This is expected.

Probably, it was not able to find any objects for the keyword part of the search.

While a vector search will always return the closest objects, the keyword search will only return matching objects.

Closing here as this is not a bug.

Thanks!

**Closed by dudanogueira** 2024-05-06 20:01 UTC
Labels: bug

**Comment by gui-uchoa** [comment] 2024-05-07 14:55
@dudanogueira What about the cases where the score only shows the keyword ones, and not the vector search?
Here's the output i got when testing hybrid search:

Hybrid (Result Set keyword) Document 3d6ba9fb-ae2b-4b2c-b3af-587f3da34092: original score 4.439258, normalized score: 0.3789217"

Is it expected too? 

Thanks!
